name: my-first-useless-snap
base: core20
version: '0.1'
summary: Restic backup server
description: |
  Restic-server is a simple server for use with the restic backup tool.

grade: devel # use 'stable' for release version
confinement: strict

apps:
  restic-server:
    command: bin/rest-server
    plugs:
      - network
      - network-bind

parts:
  restic-server:
    plugin: go
    source: https://github.com/restic/rest-server
    source-tag: v0.12.1
    build-packages:
      - git
